Repository SverigesSandareamatorer/SSA-Akademin, pull requests merged in 2019-10, with the labels that each got.

#519 Uppdatering med Läsanvisningar från Jonas och bandplaner för HF/VHF/UHF
  VERSION.txt
  koncept/appendix-o.tex
  koncept/appendix-p.tex
  koncept/koncept-core.tex
Labels: HAREC, enhancement

#520 Buggfixar och mindre uppdateringar
  README.md
  VERSION.txt
  koncept/chapter1-2.tex
  koncept/chapter13-4.tex
  koncept/chapter2-1.tex
  koncept/chapter2-2.tex
  koncept/chapter9-2.tex
  koncept/koncept-core.tex
  koncept/preface.tex
  koncept/tryckort.tex
Labels: bug, enhancement

#507 Större spelrum för microtype att justera texten
  koncept.tex
Labels: layout

#525 Bandplansuppdateringar (Layout)
  VERSION.txt
  koncept/appendix-p.tex
  koncept/chapter13-4.tex
  koncept/common.tex
Labels: bug, enhancement, layout
