Repository SverigesSandareamatorer/SSA-Akademin, pull requests merged in 2023-09, with the labels that each got.

#667 Fixa typo i ISBN på tryckkort.tex
  koncept/tryckort.tex
Labels: Typ: Bugg

#649 Förbättring av texterna om simplex och halvduplex
  CHANGELOG.md
  koncept/chapter6-2.tex
Labels: Typ: Förbättring, Område: Innehåll

#662 lägg till borttappat för
  koncept/chapter13-5.tex
Labels: Typ: Bugg, Område: Innehåll

#669 Fixa ekvationer som stoppar EPUB-genereringen
  koncept/chapter2-7.tex
Labels: Typ: Bugg, Område: Bygge, Variant: EPUB
